name: Style

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x on ubuntu-latest
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update build tools
      run: python -m pip install --upgrade pip setuptools

    - name: Install Pydra
      run: pip install ".[dev]"

    - name: Check Style
      run: |
        pip install black==21.8b0 codecov
        black --check pydra setup.py
